const _apiBase = import.meta.env.VITE_API_BASE_URL as string | undefined;

if (!_apiBase && import.meta.env.MODE === 'production') {
  console.error(
    '[Config] VITE_API_BASE_URL is not set. ' +
    'All API requests will fail. ' +
    'Set this environment variable in your Render Static Site settings and redeploy.'
  );
}

export const BASE_URL = _apiBase ?? (import.meta.env.MODE === 'production' ? '' : 'http://localhost:3001');

export const apiPaths = {
  AUTH: {
    signup: '/api/auth/register',
    login: '/api/auth/login',
    GET_USER_PROFILE: '/api/auth/profile',
    UPDATE_USER_PROFILE: '/api/auth/profile/:id',
  },
  USERS: {
    GET_ALL_USERS: '/api/users',
    GET_USER_BY_ID: '/api/users/:id',
    PERFORMANCE: '/api/users/:id/performance',
    DELETE_USER: '/api/users/:id',
  },
  TASKS: {
    GET_DASHBOARD_TASKS: '/api/tasks/dashboard-tasks',
    GET_USER_DASHBOARD_TASKS: '/api/tasks/user-dashboard-tasks',
    GET_ALL_TASKS: '/api/tasks',
    GET_TASK_BY_ID: '/api/tasks/:id',
    CREATE_TASK: '/api/tasks',
    UPDATE_TASK: '/api/tasks/:id',
    DELETE_TASK: '/api/tasks/:id',
    UPDATE_TASK_STATUS: '/api/tasks/:id/status',
    UPDATE_TASK_ASSIGNEE: '/api/tasks/:id/assignee',
    UPDATE_TASK_CHECKLIST: '/api/tasks/:id/todo',
    COMMENTS: '/api/tasks/:id/comments',
    DELETE_COMMENT: '/api/tasks/:id/comments/:commentId',
    ACTIVITY: '/api/tasks/:id/activity',
    ATTACHMENTS: '/api/tasks/:id/attachments',
    DELETE_ATTACHMENT: '/api/tasks/:id/attachments/:attachmentId',
    SUBTASKS: '/api/tasks/:id/subtasks',
    REORDER_SUBTASKS: '/api/tasks/:id/subtasks/reorder',
    TIMER_START: '/api/tasks/:id/timer/start',
    TIMER_STOP: '/api/tasks/:id/timer/stop',
    SAVE_AS_TEMPLATE: '/api/tasks/:id/save-as-template',
  },
  TIME_ENTRIES: {
    LIST: '/api/time-entries',
    REPORT: '/api/time-entries/report',
    CREATE: '/api/time-entries',
    UPDATE: '/api/time-entries/:id',
    DELETE: '/api/time-entries/:id',
  },
  TASK_TEMPLATES: {
    LIST: '/api/task-templates',
    GET: '/api/task-templates/:id',
    CREATE: '/api/task-templates',
    UPDATE: '/api/task-templates/:id',
    DELETE: '/api/task-templates/:id',
    CREATE_TASK: '/api/task-templates/:id/create-task',
  },

  SPRINTS: {
    LIST: '/api/sprints',
    GET: '/api/sprints/:id',
    CREATE: '/api/sprints',
    UPDATE: '/api/sprints/:id',
    DELETE: '/api/sprints/:id',
    TASKS: '/api/sprints/:id/tasks',
  },
  MILESTONES: {
    LIST: '/api/milestones',
    GET: '/api/milestones/:id',
    CREATE: '/api/milestones',
    UPDATE: '/api/milestones/:id',
    DELETE: '/api/milestones/:id',
    TASKS: '/api/milestones/:id/tasks',
  },
  KEY_RESULTS: {
    LIST: '/api/key-results',
    CREATE: '/api/key-results',
    UPDATE: '/api/key-results/:id',
    DELETE: '/api/key-results/:id',
  },
  PROJECTS: {
    LIST: '/api/projects',
    GET_BY_ID: '/api/projects/:id',
    GANTT: '/api/projects/:id/gantt',
    CREATE: '/api/projects',
    UPDATE: '/api/projects/:id',
    DELETE: '/api/projects/:id',
  },
  GOALS: {
    LIST: '/api/goals',
    GET_BY_ID: '/api/goals/:id',
    OKR_TREE: '/api/goals/:id/okr-tree',
    CREATE: '/api/goals',
    UPDATE: '/api/goals/:id',
    DELETE: '/api/goals/:id',
    LINK_PROJECT: '/api/goals/:id/link-project',
    UNLINK_PROJECT: '/api/goals/:id/unlink-project',
  },
  DEPENDENCIES: {
    LIST: '/api/dependencies',
    ANALYSIS: '/api/dependencies/analysis',
    CREATE: '/api/dependencies',
    DELETE: '/api/dependencies/:id',
  },
  WORKOS: {
    ORG_SUMMARY: '/api/workos/orgs/:id/summary',
    PROJECT_SUMMARY: '/api/workos/projects/:id/summary',
    USER_SUMMARY: '/api/workos/users/:id/summary',
    SCOPES: '/api/workos/scopes',
    EXECUTE_ACTION: '/api/workos/actions/execute',
  },
  AUTOMATION: {
    LIST_RULES: '/api/automation/rules',
    CREATE_RULE: '/api/automation/rules',
    UPDATE_RULE: '/api/automation/rules/:id',
    DELETE_RULE: '/api/automation/rules/:id',
    DAILY_SUMMARY_JOB: '/api/automation/jobs/daily-summary',
  },
  REPORTS: {
    SUMMARY: '/api/reports/summary',
    ANALYTICS: '/api/reports/analytics',
    TRENDS: '/api/reports/trends',
    TEAM_PERFORMANCE: '/api/reports/team-performance',
    SPRINT_VELOCITY: '/api/reports/sprint-velocity',
    BURNDOWN: '/api/reports/burndown',
    CUMULATIVE_FLOW: '/api/reports/cumulative-flow',
    PROJECT_HEALTH: '/api/reports/project-health',
    WORKLOAD_HEATMAP: '/api/reports/workload-heatmap',
    Export_TASKS_REPORT: '/api/reports/export-tasks',
    Export_USERS_REPORT: '/api/reports/export-users',
    Export_PROJECTS_REPORT: '/api/reports/export-projects',
    Export_GOALS_REPORT: '/api/reports/export-goals',
  },
  UPLOADS: {
    UPLOAD_IMAGE: '/api/auth/upload-image',
  },
  ORG_MEMBERSHIP: {
    MY_ORGS: '/api/org-membership/my-orgs',
    LEAVE_ORG: '/api/org-membership/:orgId/leave',
    INVITE: '/api/org-membership/:orgId/invite',
    JOIN: '/api/org-membership/join',
    GET_MEMBERS: '/api/org-membership/:orgId/members',
    UPDATE_ROLE: '/api/org-membership/:orgId/members/:memberId/role',
    REMOVE_MEMBER: '/api/org-membership/:orgId/members/:memberId',
  },
  ORGS: {
    CREATE: '/api/orgs',
    TEMPLATES: '/api/orgs/templates',
    GET_BY_ID: '/api/orgs/:orgId',
    UPDATE: '/api/orgs/:orgId',
    DELETE: '/api/orgs/:orgId',
    ADD_MEMBER: '/api/orgs/:orgId/add-member',
    CHECK_USER: '/api/orgs/check-user/:email',
  },
  TEAMS: {
    LIST: '/api/teams',
    GET: '/api/teams/:id',
    DASHBOARD: '/api/teams/:id/dashboard',
    CREATE: '/api/teams',
    UPDATE: '/api/teams/:id',
    DELETE: '/api/teams/:id',
  },
  ROLES: {
    CATALOG: '/api/roles/catalog',
    ME: '/api/roles/me',
    LIST: '/api/roles',
    CREATE: '/api/roles',
    UPDATE: '/api/roles/:id',
    DELETE: '/api/roles/:id',
  },
  AUDIT: {
    LIST: '/api/audit-logs',
    EXPORT: '/api/audit-logs/export',
  },
  NOTIFICATIONS: {
    LIST: '/api/notifications',
    READ: '/api/notifications/:id/read',
    UNREAD: '/api/notifications/:id/unread',
    READ_ALL: '/api/notifications/read-all',
    DELETE: '/api/notifications/:id',
    CLEAR: '/api/notifications/clear',
    PREFERENCES: '/api/notifications/preferences',
    PRESENCE: '/api/notifications/presence',
  },
};
